openapi: 3.0.0
info:
  version: 0.1.0
  title: Chess API
  description: A simple API to interact with Chess server

servers:
  - url: https://localhost:8080/

security:
  - BasicAuth: []

paths: 
  /user:
    post:
      description: Register a new user
      requestBody: 
        content:
          'application/json':
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: Successfully registered new user
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  authToken:
                    type: string
        '400':
          $ref: '#/components/responses/400Error'
  
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  
  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
